-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input21_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    input21_empty_n : IN STD_LOGIC;
    input21_read : OUT STD_LOGIC;
    obj_hgt_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    obj_hgt_empty_n : IN STD_LOGIC;
    obj_hgt_read : OUT STD_LOGIC;
    obj_wdt_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    obj_wdt_empty_n : IN STD_LOGIC;
    obj_wdt_read : OUT STD_LOGIC;
    Qu_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    Qu_ce0 : OUT STD_LOGIC;
    Qu_we0 : OUT STD_LOGIC;
    Qu_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_read : IN STD_LOGIC_VECTOR (3 downto 0);
    Pu_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    Pu_ce0 : OUT STD_LOGIC;
    Pu_we0 : OUT STD_LOGIC;
    Pu_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    BIN_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    BIN_ce0 : OUT STD_LOGIC;
    BIN_we0 : OUT STD_LOGIC;
    BIN_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    BIN1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    BIN1_ce0 : OUT STD_LOGIC;
    BIN1_we0 : OUT STD_LOGIC;
    BIN1_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_ext_blocking_n : OUT STD_LOGIC;
    ap_str_blocking_n : OUT STD_LOGIC;
    ap_int_blocking_n : OUT STD_LOGIC );
end;


architecture behav of mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv9_1F0 : STD_LOGIC_VECTOR (8 downto 0) := "111110000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal xFTrackmulKernelLut_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal xFTrackmulKernelLut_ce0 : STD_LOGIC;
    signal xFTrackmulKernelLut_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal obj_hgt_blk_n : STD_LOGIC;
    signal obj_wdt_blk_n : STD_LOGIC;
    signal obj_wdt_read_reg_374 : STD_LOGIC_VECTOR (15 downto 0);
    signal obj_hgt_read_reg_379 : STD_LOGIC_VECTOR (15 downto 0);
    signal h_y_reg_384 : STD_LOGIC_VECTOR (14 downto 0);
    signal h_x_reg_390 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_height1_reg_397 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln223_fu_226_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln223_reg_402 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_width1_reg_407 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln223_1_fu_243_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln223_1_reg_412 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_reg_417 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_fu_253_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_reg_427 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln214_fu_261_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln214_reg_432 : STD_LOGIC_VECTOR (18 downto 0);
    signal buf_size_fu_271_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_size_reg_437 : STD_LOGIC_VECTOR (15 downto 0);
    signal wh_fu_287_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal wh_reg_442 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln232_1_fu_291_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln232_1_reg_447 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal y_2_fu_339_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_2_reg_460 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln232_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp49_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp49_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_362_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal y_off_reg_475 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal xFTrackmulKernelLut_load_reg_480 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hist1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hist1_ce0 : STD_LOGIC;
    signal tmp_hist1_we0 : STD_LOGIC;
    signal tmp_hist1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_hist1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_hist2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hist2_ce0 : STD_LOGIC;
    signal tmp_hist2_we0 : STD_LOGIC;
    signal tmp_hist2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_hist2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Inverse_fu_145_ap_start : STD_LOGIC;
    signal grp_Inverse_fu_145_ap_done : STD_LOGIC;
    signal grp_Inverse_fu_145_ap_idle : STD_LOGIC;
    signal grp_Inverse_fu_145_ap_ready : STD_LOGIC;
    signal grp_Inverse_fu_145_x : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_Inverse_fu_145_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Inverse_fu_145_ap_return_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Inverse_fu_145_ap_ext_blocking_n : STD_LOGIC;
    signal grp_Inverse_fu_145_ap_str_blocking_n : STD_LOGIC;
    signal grp_Inverse_fu_145_ap_int_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_idle : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ready : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_idle : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ready : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_idle : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ready : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_ce0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_we0 : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_d0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n : STD_LOGIC;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n : STD_LOGIC;
    signal grp_Inverse_fu_145_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg : STD_LOGIC := '0';
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal idxprom24_i_fu_358_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_96 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_8_fu_310_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal sext_ln223_1_fu_222_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln223_2_fu_240_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln223_fu_236_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sext_ln223_3_fu_264_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln222_fu_278_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln223_fu_267_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lshr_ln223_fu_281_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln232_2_fu_301_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal a_fu_316_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_fu_329_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_321_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_66_fu_333_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_362_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_362_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_int_blocking_cur_n : STD_LOGIC;
    signal ap_ext_blocking_sub_n : STD_LOGIC;
    signal ap_wait_0 : STD_LOGIC;
    signal ap_sub_ext_blocking_0 : STD_LOGIC;
    signal ap_wait_1 : STD_LOGIC;
    signal ap_sub_ext_blocking_1 : STD_LOGIC;
    signal ap_wait_2 : STD_LOGIC;
    signal ap_sub_ext_blocking_2 : STD_LOGIC;
    signal ap_wait_3 : STD_LOGIC;
    signal ap_sub_ext_blocking_3 : STD_LOGIC;
    signal ap_str_blocking_sub_n : STD_LOGIC;
    signal ap_sub_str_blocking_0 : STD_LOGIC;
    signal ap_sub_str_blocking_1 : STD_LOGIC;
    signal ap_sub_str_blocking_2 : STD_LOGIC;
    signal ap_sub_str_blocking_3 : STD_LOGIC;
    signal ap_int_blocking_sub_n : STD_LOGIC;
    signal ap_sub_int_blocking_0 : STD_LOGIC;
    signal ap_sub_int_blocking_1 : STD_LOGIC;
    signal ap_sub_int_blocking_2 : STD_LOGIC;
    signal ap_sub_int_blocking_3 : STD_LOGIC;
    signal grp_fu_362_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mean_shift_accel_Inverse IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x : IN STD_LOGIC_VECTOR (14 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC );
    end component;


    component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        tmp_hist1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        tmp_hist1_ce0 : OUT STD_LOGIC;
        tmp_hist1_we0 : OUT STD_LOGIC;
        tmp_hist1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_hist2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        tmp_hist2_ce0 : OUT STD_LOGIC;
        tmp_hist2_we0 : OUT STD_LOGIC;
        tmp_hist2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC );
    end component;


    component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln268 : IN STD_LOGIC_VECTOR (12 downto 0);
        Qu_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        Qu_ce0 : OUT STD_LOGIC;
        Qu_we0 : OUT STD_LOGIC;
        Qu_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_hist1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        tmp_hist1_ce0 : OUT STD_LOGIC;
        tmp_hist1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_hist2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        tmp_hist2_ce0 : OUT STD_LOGIC;
        tmp_hist2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        cmp49 : IN STD_LOGIC_VECTOR (0 downto 0);
        Pu_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        Pu_ce0 : OUT STD_LOGIC;
        Pu_we0 : OUT STD_LOGIC;
        Pu_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC );
    end component;


    component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input21_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        input21_empty_n : IN STD_LOGIC;
        input21_read : OUT STD_LOGIC;
        buf_size : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln222 : IN STD_LOGIC_VECTOR (14 downto 0);
        yy_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        wh : IN STD_LOGIC_VECTOR (23 downto 0);
        tmp_hist1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        tmp_hist1_ce0 : OUT STD_LOGIC;
        tmp_hist1_we0 : OUT STD_LOGIC;
        tmp_hist1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_hist1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_hist2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        tmp_hist2_ce0 : OUT STD_LOGIC;
        tmp_hist2_we0 : OUT STD_LOGIC;
        tmp_hist2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_hist2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        y_off : IN STD_LOGIC_VECTOR (18 downto 0);
        BIN_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        BIN_ce0 : OUT STD_LOGIC;
        BIN_we0 : OUT STD_LOGIC;
        BIN_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        BIN1_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        BIN1_ce0 : OUT STD_LOGIC;
        BIN1_we0 : OUT STD_LOGIC;
        BIN1_d0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        ap_ext_blocking_n : OUT STD_LOGIC;
        ap_str_blocking_n : OUT STD_LOGIC;
        ap_int_blocking_n : OUT STD_LOGIC );
    end component;


    component mean_shift_accel_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mean_shift_accel_mul_mul_16ns_16ns_19_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_histdEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s_tmp_hist1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    xFTrackmulKernelLut_U : component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_histdEe
    generic map (
        DataWidth => 16,
        AddressRange => 200,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => xFTrackmulKernelLut_address0,
        ce0 => xFTrackmulKernelLut_ce0,
        q0 => xFTrackmulKernelLut_q0);

    tmp_hist1_U : component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s_tmp_hist1
    generic map (
        DataWidth => 32,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tmp_hist1_address0,
        ce0 => tmp_hist1_ce0,
        we0 => tmp_hist1_we0,
        d0 => tmp_hist1_d0,
        q0 => tmp_hist1_q0);

    tmp_hist2_U : component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s_tmp_hist1
    generic map (
        DataWidth => 32,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tmp_hist2_address0,
        ce0 => tmp_hist2_ce0,
        we0 => tmp_hist2_we0,
        d0 => tmp_hist2_d0,
        q0 => tmp_hist2_q0);

    grp_Inverse_fu_145 : component mean_shift_accel_Inverse
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Inverse_fu_145_ap_start,
        ap_done => grp_Inverse_fu_145_ap_done,
        ap_idle => grp_Inverse_fu_145_ap_idle,
        ap_ready => grp_Inverse_fu_145_ap_ready,
        x => grp_Inverse_fu_145_x,
        ap_return_0 => grp_Inverse_fu_145_ap_return_0,
        ap_return_1 => grp_Inverse_fu_145_ap_return_1,
        ap_ext_blocking_n => grp_Inverse_fu_145_ap_ext_blocking_n,
        ap_str_blocking_n => grp_Inverse_fu_145_ap_str_blocking_n,
        ap_int_blocking_n => grp_Inverse_fu_145_ap_int_blocking_n);

    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152 : component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start,
        ap_done => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done,
        ap_idle => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_idle,
        ap_ready => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ready,
        tmp_hist1_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0,
        tmp_hist1_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0,
        tmp_hist1_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0,
        tmp_hist1_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0,
        tmp_hist2_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0,
        tmp_hist2_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0,
        tmp_hist2_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0,
        tmp_hist2_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0,
        ap_ext_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n,
        ap_str_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n,
        ap_int_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n);

    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158 : component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start,
        ap_done => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done,
        ap_idle => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_idle,
        ap_ready => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ready,
        zext_ln268 => tmp_reg_427,
        Qu_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_address0,
        Qu_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_ce0,
        Qu_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_we0,
        Qu_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_d0,
        tmp_hist1_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0,
        tmp_hist1_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0,
        tmp_hist1_q0 => tmp_hist1_q0,
        tmp_hist2_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0,
        tmp_hist2_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0,
        tmp_hist2_q0 => tmp_hist2_q0,
        cmp49 => cmp49_reg_465,
        Pu_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_address0,
        Pu_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_ce0,
        Pu_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_we0,
        Pu_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_d0,
        ap_ext_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n,
        ap_str_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n,
        ap_int_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n);

    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170 : component mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start,
        ap_done => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done,
        ap_idle => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_idle,
        ap_ready => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ready,
        input21_dout => input21_dout,
        input21_empty_n => input21_empty_n,
        input21_read => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read,
        buf_size => buf_size_reg_437,
        zext_ln222 => h_x_reg_390,
        yy_cast => xFTrackmulKernelLut_load_reg_480,
        wh => wh_reg_442,
        tmp_hist1_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0,
        tmp_hist1_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0,
        tmp_hist1_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0,
        tmp_hist1_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0,
        tmp_hist1_q0 => tmp_hist1_q0,
        tmp_hist2_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0,
        tmp_hist2_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0,
        tmp_hist2_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0,
        tmp_hist2_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0,
        tmp_hist2_q0 => tmp_hist2_q0,
        y_off => y_off_reg_475,
        BIN_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_address0,
        BIN_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_ce0,
        BIN_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_we0,
        BIN_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_d0,
        BIN1_address0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_address0,
        BIN1_ce0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_ce0,
        BIN1_we0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_we0,
        BIN1_d0 => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_d0,
        ap_ext_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n,
        ap_str_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n,
        ap_int_blocking_n => grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n);

    mul_32s_32s_32_2_1_U85 : component mean_shift_accel_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_width1_reg_407,
        din1 => p_height1_reg_397,
        ce => ap_const_logic_1,
        dout => grp_fu_249_p2);

    mul_mul_16ns_16ns_19_4_1_U86 : component mean_shift_accel_mul_mul_16ns_16ns_19_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_362_p0,
        din1 => grp_fu_362_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_362_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Inverse_fu_145_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Inverse_fu_145_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                    grp_Inverse_fu_145_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Inverse_fu_145_ap_ready = ap_const_logic_1)) then 
                    grp_Inverse_fu_145_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln232_fu_305_p2 = ap_const_lv1_1))) then 
                    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ready = ap_const_logic_1)) then 
                    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ready = ap_const_logic_1)) then 
                    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ready = ap_const_logic_1)) then 
                    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((obj_wdt_empty_n = ap_const_logic_0) or (obj_hgt_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_96 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln232_fu_305_p2 = ap_const_lv1_0))) then 
                i_fu_96 <= i_8_fu_310_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln223_1_reg_412 <= add_ln223_1_fu_243_p2;
                p_width1_reg_407 <= grp_Inverse_fu_145_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln223_reg_402 <= add_ln223_fu_226_p2;
                p_height1_reg_397 <= grp_Inverse_fu_145_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                    buf_size_reg_437(15 downto 1) <= buf_size_fu_271_p3(15 downto 1);
                    tmp_reg_427(12 downto 9) <= tmp_fu_253_p3(12 downto 9);
                wh_reg_442 <= wh_fu_287_p1;
                    zext_ln214_reg_432(15 downto 0) <= zext_ln214_fu_261_p1(15 downto 0);
                    zext_ln232_1_reg_447(14 downto 0) <= zext_ln232_1_fu_291_p1(14 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln232_fu_305_p2 = ap_const_lv1_1))) then
                cmp49_reg_465 <= cmp49_fu_352_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                h_x_reg_390 <= obj_wdt_dout(15 downto 1);
                h_y_reg_384 <= obj_hgt_dout(15 downto 1);
                obj_hgt_read_reg_379 <= obj_hgt_dout;
                obj_wdt_read_reg_374 <= obj_wdt_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                temp_reg_417 <= grp_fu_249_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                xFTrackmulKernelLut_load_reg_480 <= xFTrackmulKernelLut_q0;
                y_off_reg_475 <= grp_fu_362_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln232_fu_305_p2 = ap_const_lv1_0))) then
                y_2_reg_460 <= y_2_fu_339_p3;
            end if;
        end if;
    end process;
    tmp_reg_427(8 downto 0) <= "000000000";
    zext_ln214_reg_432(18 downto 16) <= "000";
    buf_size_reg_437(0) <= '0';
    zext_ln232_1_reg_447(16 downto 15) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, obj_hgt_empty_n, obj_wdt_empty_n, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state8, icmp_ln232_fu_305_p2, grp_Inverse_fu_145_ap_done, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done, ap_block_state3_on_subcall_done, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((obj_wdt_empty_n = ap_const_logic_0) or (obj_hgt_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_Inverse_fu_145_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln232_fu_305_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    BIN1_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_address0;
    BIN1_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_ce0;
    BIN1_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_d0;
    BIN1_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_we0;
    BIN_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_address0;
    BIN_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_ce0;
    BIN_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_d0;
    BIN_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_we0;
    Pu_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_address0;
    Pu_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_ce0;
    Pu_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_d0;
    Pu_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_we0;
    Qu_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_address0;
    Qu_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_ce0;
    Qu_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_d0;
    Qu_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_we0;
    a_fu_316_p2 <= std_logic_vector(unsigned(zext_ln232_2_fu_301_p1) - unsigned(zext_ln232_1_reg_447));
    add_ln223_1_fu_243_p2 <= std_logic_vector(signed(sext_ln223_2_fu_240_p1) + signed(sext_ln223_fu_236_p1));
    add_ln223_fu_226_p2 <= std_logic_vector(signed(sext_ln223_1_fu_222_p1) + signed(ap_const_lv9_1F0));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state14_blk_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, obj_hgt_empty_n, obj_wdt_empty_n)
    begin
        if (((obj_wdt_empty_n = ap_const_logic_0) or (obj_hgt_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(grp_Inverse_fu_145_ap_done)
    begin
        if ((grp_Inverse_fu_145_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, obj_hgt_empty_n, obj_wdt_empty_n)
    begin
                ap_block_state1 <= ((obj_wdt_empty_n = ap_const_logic_0) or (obj_hgt_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_Inverse_fu_145_ap_done, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done = ap_const_logic_0) or (grp_Inverse_fu_145_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_ext_blocking_n <= (ap_ext_blocking_sub_n and ap_const_logic_1);

    ap_ext_blocking_sub_n_assign_proc : process(ap_wait_0, ap_sub_ext_blocking_0, ap_wait_1, ap_sub_ext_blocking_1, ap_wait_2, ap_sub_ext_blocking_2, ap_wait_3, ap_sub_ext_blocking_3)
    begin
        if ((((ap_wait_3 and ap_sub_ext_blocking_3) = ap_const_logic_1) and ((ap_wait_2 and ap_sub_ext_blocking_2) = ap_const_logic_1) and ((ap_wait_1 and ap_sub_ext_blocking_1) = ap_const_logic_1) and ((ap_wait_0 and ap_sub_ext_blocking_0) = ap_const_logic_1))) then 
            ap_ext_blocking_sub_n <= ap_const_logic_0;
        else 
            ap_ext_blocking_sub_n <= ap_const_logic_1;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_int_blocking_cur_n <= (obj_wdt_blk_n and obj_hgt_blk_n);
    ap_int_blocking_n <= (ap_int_blocking_sub_n and ap_int_blocking_cur_n);

    ap_int_blocking_sub_n_assign_proc : process(ap_wait_0, ap_wait_1, ap_wait_2, ap_wait_3, ap_sub_int_blocking_0, ap_sub_int_blocking_1, ap_sub_int_blocking_2, ap_sub_int_blocking_3)
    begin
        if ((((ap_wait_3 and ap_sub_int_blocking_3) = ap_const_logic_1) and ((ap_wait_2 and ap_sub_int_blocking_2) = ap_const_logic_1) and ((ap_wait_1 and ap_sub_int_blocking_1) = ap_const_logic_1) and ((ap_wait_0 and ap_sub_int_blocking_0) = ap_const_logic_1))) then 
            ap_int_blocking_sub_n <= ap_const_logic_0;
        else 
            ap_int_blocking_sub_n <= ap_const_logic_1;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_str_blocking_n <= (ap_str_blocking_sub_n and ap_const_logic_1);

    ap_str_blocking_sub_n_assign_proc : process(ap_wait_0, ap_wait_1, ap_wait_2, ap_wait_3, ap_sub_str_blocking_0, ap_sub_str_blocking_1, ap_sub_str_blocking_2, ap_sub_str_blocking_3)
    begin
        if ((((ap_wait_3 and ap_sub_str_blocking_3) = ap_const_logic_1) and ((ap_wait_2 and ap_sub_str_blocking_2) = ap_const_logic_1) and ((ap_wait_1 and ap_sub_str_blocking_1) = ap_const_logic_1) and ((ap_wait_0 and ap_sub_str_blocking_0) = ap_const_logic_1))) then 
            ap_str_blocking_sub_n <= ap_const_logic_0;
        else 
            ap_str_blocking_sub_n <= ap_const_logic_1;
        end if; 
    end process;


    ap_sub_ext_blocking_0_assign_proc : process(grp_Inverse_fu_145_ap_ext_blocking_n)
    begin
        if ((grp_Inverse_fu_145_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_0 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_ext_blocking_1_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_1 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_ext_blocking_2_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_2 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_ext_blocking_3_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n = ap_const_logic_0)) then 
            ap_sub_ext_blocking_3 <= ap_const_logic_1;
        else 
            ap_sub_ext_blocking_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_0_assign_proc : process(grp_Inverse_fu_145_ap_int_blocking_n)
    begin
        if ((grp_Inverse_fu_145_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_0 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_1_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_1 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_2_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_2 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_int_blocking_3_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n = ap_const_logic_0)) then 
            ap_sub_int_blocking_3 <= ap_const_logic_1;
        else 
            ap_sub_int_blocking_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_0_assign_proc : process(grp_Inverse_fu_145_ap_str_blocking_n)
    begin
        if ((grp_Inverse_fu_145_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_0 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_1_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_1 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_2_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_2 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sub_str_blocking_3_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n)
    begin
        if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n = ap_const_logic_0)) then 
            ap_sub_str_blocking_3 <= ap_const_logic_1;
        else 
            ap_sub_str_blocking_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_0_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state3 = ap_CS_fsm)) then 
            ap_wait_0 <= ap_const_logic_1;
        else 
            ap_wait_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_1_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state3 = ap_CS_fsm)) then 
            ap_wait_1 <= ap_const_logic_1;
        else 
            ap_wait_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_2_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state14 = ap_CS_fsm)) then 
            ap_wait_2 <= ap_const_logic_1;
        else 
            ap_wait_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_wait_3_assign_proc : process(ap_CS_fsm)
    begin
        if ((ap_ST_fsm_state13 = ap_CS_fsm)) then 
            ap_wait_3 <= ap_const_logic_1;
        else 
            ap_wait_3 <= ap_const_logic_0;
        end if; 
    end process;

    buf_size_fu_271_p3 <= (h_x_reg_390 & ap_const_lv1_0);
    cmp49_fu_352_p2 <= "1" when (p_read1 = ap_const_lv8_0) else "0";
    empty_66_fu_333_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(empty_fu_329_p1));
    empty_fu_329_p1 <= a_fu_316_p2(8 - 1 downto 0);
    grp_Inverse_fu_145_ap_start <= grp_Inverse_fu_145_ap_start_reg;

    grp_Inverse_fu_145_x_assign_proc : process(h_y_reg_384, h_x_reg_390, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_Inverse_fu_145_x <= h_x_reg_390;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_Inverse_fu_145_x <= h_y_reg_384;
        else 
            grp_Inverse_fu_145_x <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_362_p0 <= grp_fu_362_p00(16 - 1 downto 0);
    grp_fu_362_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_96),19));
    grp_fu_362_p1 <= zext_ln214_reg_432(16 - 1 downto 0);
    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg;
    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg;
    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg;
    i_8_fu_310_p2 <= std_logic_vector(unsigned(i_fu_96) + unsigned(ap_const_lv16_1));
    icmp_ln232_fu_305_p2 <= "1" when (i_fu_96 = obj_hgt_read_reg_379) else "0";
    idxprom24_i_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_2_reg_460),64));

    input21_read_assign_proc : process(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            input21_read <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read;
        else 
            input21_read <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln223_fu_281_p2 <= std_logic_vector(shift_right(unsigned(zext_ln222_fu_278_p1),to_integer(unsigned('0' & zext_ln223_fu_267_p1(31-1 downto 0)))));

    obj_hgt_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, obj_hgt_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            obj_hgt_blk_n <= obj_hgt_empty_n;
        else 
            obj_hgt_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    obj_hgt_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, obj_hgt_empty_n, obj_wdt_empty_n)
    begin
        if ((not(((obj_wdt_empty_n = ap_const_logic_0) or (obj_hgt_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            obj_hgt_read <= ap_const_logic_1;
        else 
            obj_hgt_read <= ap_const_logic_0;
        end if; 
    end process;


    obj_wdt_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, obj_wdt_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            obj_wdt_blk_n <= obj_wdt_empty_n;
        else 
            obj_wdt_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    obj_wdt_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, obj_hgt_empty_n, obj_wdt_empty_n)
    begin
        if ((not(((obj_wdt_empty_n = ap_const_logic_0) or (obj_hgt_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            obj_wdt_read <= ap_const_logic_1;
        else 
            obj_wdt_read <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln223_1_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_Inverse_fu_145_ap_return_1),9));

        sext_ln223_2_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln223_reg_402),10));

        sext_ln223_3_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln223_1_reg_412),32));

        sext_ln223_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_Inverse_fu_145_ap_return_1),10));

    tmp_7_fu_321_p3 <= a_fu_316_p2(16 downto 16);
    tmp_fu_253_p3 <= (p_read & ap_const_lv9_0);

    tmp_hist1_address0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist1_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            tmp_hist1_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist1_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0;
        else 
            tmp_hist1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    tmp_hist1_ce0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist1_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            tmp_hist1_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist1_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0;
        else 
            tmp_hist1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tmp_hist1_d0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist1_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist1_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0;
        else 
            tmp_hist1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_hist1_we0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist1_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist1_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0;
        else 
            tmp_hist1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    tmp_hist2_address0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist2_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            tmp_hist2_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist2_address0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0;
        else 
            tmp_hist2_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    tmp_hist2_ce0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist2_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            tmp_hist2_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist2_ce0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0;
        else 
            tmp_hist2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tmp_hist2_d0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist2_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist2_d0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0;
        else 
            tmp_hist2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_hist2_we0_assign_proc : process(ap_CS_fsm_state3, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0, grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            tmp_hist2_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            tmp_hist2_we0 <= grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0;
        else 
            tmp_hist2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    wh_fu_287_p1 <= lshr_ln223_fu_281_p2(24 - 1 downto 0);

    xFTrackmulKernelLut_address0_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13, idxprom24_i_fu_358_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            xFTrackmulKernelLut_address0 <= idxprom24_i_fu_358_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            xFTrackmulKernelLut_address0 <= ap_const_lv8_0;
        else 
            xFTrackmulKernelLut_address0 <= "XXXXXXXX";
        end if; 
    end process;


    xFTrackmulKernelLut_ce0_assign_proc : process(ap_CS_fsm_state10, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            xFTrackmulKernelLut_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            xFTrackmulKernelLut_ce0 <= ap_const_logic_0;
        else 
            xFTrackmulKernelLut_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    y_2_fu_339_p3 <= 
        empty_66_fu_333_p2 when (tmp_7_fu_321_p3(0) = '1') else 
        empty_fu_329_p1;
    zext_ln214_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(obj_wdt_read_reg_374),19));
    zext_ln222_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(temp_reg_417),64));
    zext_ln223_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln223_3_fu_264_p1),64));
    zext_ln232_1_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(h_y_reg_384),17));
    zext_ln232_2_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_96),17));
end behav;
