-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mean_shift_accel_Inverse_Pipeline_VITIS_LOOP_3039_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln3036 : IN STD_LOGIC_VECTOR (2 downto 0);
    tmp_8_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    tmp_8_out_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_ext_blocking_n : OUT STD_LOGIC;
    ap_str_blocking_n : OUT STD_LOGIC;
    ap_int_blocking_n : OUT STD_LOGIC );
end;


architecture behav of mean_shift_accel_Inverse_Pipeline_VITIS_LOOP_3039_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln3045_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln3039_fu_77_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_phi_mux_UnifiedRetVal_phi_fu_61_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_40 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_tmp_11 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_12_fu_83_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln3039_fu_90_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln3044_fu_94_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln3044cast_fu_100_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln3044_fu_104_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mean_shift_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mean_shift_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1) and ((icmp_ln3039_fu_77_p2 = ap_const_lv1_1) or (icmp_ln3045_fu_110_p2 = ap_const_lv1_0)))) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_61_p4;
                end if; 
            end if;
        end if;
    end process;


    tmp_fu_40_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if (((icmp_ln3039_fu_77_p2 = ap_const_lv1_0) and (icmp_ln3045_fu_110_p2 = ap_const_lv1_1))) then 
                    tmp_fu_40 <= tmp_12_fu_83_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    tmp_fu_40 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln3045_fu_110_p2, icmp_ln3039_fu_77_p2, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1) and ((icmp_ln3039_fu_77_p2 = ap_const_lv1_1) or (icmp_ln3045_fu_110_p2 = ap_const_lv1_0)))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_ext_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);

    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_int_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);
    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_UnifiedRetVal_phi_fu_61_p4_assign_proc : process(ap_CS_fsm_state1, icmp_ln3045_fu_110_p2, icmp_ln3039_fu_77_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if (((icmp_ln3039_fu_77_p2 = ap_const_lv1_0) and (icmp_ln3045_fu_110_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_61_p4 <= ap_const_lv1_0;
            elsif ((icmp_ln3039_fu_77_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_61_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_UnifiedRetVal_phi_fu_61_p4 <= "X";
            end if;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_61_p4 <= "X";
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state1, icmp_ln3045_fu_110_p2, icmp_ln3039_fu_77_p2, ap_phi_mux_UnifiedRetVal_phi_fu_61_p4, ap_return_preg, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1) and ((icmp_ln3039_fu_77_p2 = ap_const_lv1_1) or (icmp_ln3045_fu_110_p2 = ap_const_lv1_0)))) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_61_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    ap_sig_allocacmp_tmp_11_assign_proc : process(ap_CS_fsm_state1, tmp_fu_40, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_tmp_11 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_tmp_11 <= tmp_fu_40;
        end if; 
    end process;

    ap_str_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);
    icmp_ln3039_fu_77_p2 <= "1" when (ap_sig_allocacmp_tmp_11 = ap_const_lv3_4) else "0";
    icmp_ln3045_fu_110_p2 <= "1" when (lshr_ln3044_fu_104_p2 = ap_const_lv3_0) else "0";
    lshr_ln3044_fu_104_p2 <= std_logic_vector(shift_right(unsigned(zext_ln3036),to_integer(unsigned('0' & xor_ln3044cast_fu_100_p1(3-1 downto 0)))));
    tmp_12_fu_83_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_tmp_11) + unsigned(ap_const_lv3_1));

    tmp_8_out_assign_proc : process(ap_CS_fsm_state1, icmp_ln3045_fu_110_p2, icmp_ln3039_fu_77_p2, tmp_12_fu_83_p2, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
            if ((icmp_ln3039_fu_77_p2 = ap_const_lv1_1)) then 
                tmp_8_out <= ap_const_lv3_5;
            elsif (((icmp_ln3039_fu_77_p2 = ap_const_lv1_0) and (icmp_ln3045_fu_110_p2 = ap_const_lv1_0))) then 
                tmp_8_out <= tmp_12_fu_83_p2;
            else 
                tmp_8_out <= "XXX";
            end if;
        else 
            tmp_8_out <= "XXX";
        end if; 
    end process;


    tmp_8_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln3045_fu_110_p2, icmp_ln3039_fu_77_p2, ap_start_int)
    begin
        if ((((icmp_ln3039_fu_77_p2 = ap_const_lv1_0) and (icmp_ln3045_fu_110_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((icmp_ln3039_fu_77_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            tmp_8_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln3039_fu_90_p1 <= ap_sig_allocacmp_tmp_11(2 - 1 downto 0);
    xor_ln3044_fu_94_p2 <= (trunc_ln3039_fu_90_p1 xor ap_const_lv2_3);
    xor_ln3044cast_fu_100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln3044_fu_94_p2),3));
end behav;
