// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input21_dout,
        input21_empty_n,
        input21_read,
        obj_hgt_dout,
        obj_hgt_empty_n,
        obj_hgt_read,
        obj_wdt_dout,
        obj_wdt_empty_n,
        obj_wdt_read,
        Qu_address0,
        Qu_ce0,
        Qu_we0,
        Qu_d0,
        p_read,
        Pu_address0,
        Pu_ce0,
        Pu_we0,
        Pu_d0,
        BIN_address0,
        BIN_ce0,
        BIN_we0,
        BIN_d0,
        BIN1_address0,
        BIN1_ce0,
        BIN1_we0,
        BIN1_d0,
        p_read1,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] input21_dout;
input   input21_empty_n;
output   input21_read;
input  [15:0] obj_hgt_dout;
input   obj_hgt_empty_n;
output   obj_hgt_read;
input  [15:0] obj_wdt_dout;
input   obj_wdt_empty_n;
output   obj_wdt_read;
output  [12:0] Qu_address0;
output   Qu_ce0;
output   Qu_we0;
output  [31:0] Qu_d0;
input  [3:0] p_read;
output  [8:0] Pu_address0;
output   Pu_ce0;
output   Pu_we0;
output  [31:0] Pu_d0;
output  [17:0] BIN_address0;
output   BIN_ce0;
output   BIN_we0;
output  [8:0] BIN_d0;
output  [17:0] BIN1_address0;
output   BIN1_ce0;
output   BIN1_we0;
output  [8:0] BIN1_d0;
input  [7:0] p_read1;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input21_read;
reg obj_hgt_read;
reg obj_wdt_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] xFTrackmulKernelLut_address0;
reg    xFTrackmulKernelLut_ce0;
wire   [15:0] xFTrackmulKernelLut_q0;
reg    obj_hgt_blk_n;
reg    obj_wdt_blk_n;
reg   [15:0] obj_wdt_read_reg_374;
reg   [15:0] obj_hgt_read_reg_379;
reg   [14:0] h_y_reg_384;
reg   [14:0] h_x_reg_390;
reg  signed [31:0] p_height1_reg_397;
wire    ap_CS_fsm_state3;
wire   [8:0] add_ln223_fu_226_p2;
reg   [8:0] add_ln223_reg_402;
reg  signed [31:0] p_width1_reg_407;
wire    ap_CS_fsm_state4;
wire   [9:0] add_ln223_1_fu_243_p2;
reg   [9:0] add_ln223_1_reg_412;
wire   [31:0] grp_fu_249_p2;
reg   [31:0] temp_reg_417;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [12:0] tmp_fu_253_p3;
reg   [12:0] tmp_reg_427;
wire   [18:0] zext_ln214_fu_261_p1;
reg   [18:0] zext_ln214_reg_432;
wire   [15:0] buf_size_fu_271_p3;
reg   [15:0] buf_size_reg_437;
wire   [23:0] wh_fu_287_p1;
reg   [23:0] wh_reg_442;
wire   [16:0] zext_ln232_1_fu_291_p1;
reg   [16:0] zext_ln232_1_reg_447;
wire    ap_CS_fsm_state8;
wire   [7:0] y_2_fu_339_p3;
reg   [7:0] y_2_reg_460;
wire   [0:0] icmp_ln232_fu_305_p2;
wire   [0:0] cmp49_fu_352_p2;
reg   [0:0] cmp49_reg_465;
wire    ap_CS_fsm_state10;
wire  signed [18:0] grp_fu_362_p2;
reg   [18:0] y_off_reg_475;
wire    ap_CS_fsm_state11;
reg   [15:0] xFTrackmulKernelLut_load_reg_480;
reg   [8:0] tmp_hist1_address0;
reg    tmp_hist1_ce0;
reg    tmp_hist1_we0;
reg   [31:0] tmp_hist1_d0;
wire   [31:0] tmp_hist1_q0;
reg   [8:0] tmp_hist2_address0;
reg    tmp_hist2_ce0;
reg    tmp_hist2_we0;
reg   [31:0] tmp_hist2_d0;
wire   [31:0] tmp_hist2_q0;
wire    grp_Inverse_fu_145_ap_start;
wire    grp_Inverse_fu_145_ap_done;
wire    grp_Inverse_fu_145_ap_idle;
wire    grp_Inverse_fu_145_ap_ready;
reg   [14:0] grp_Inverse_fu_145_x;
wire   [31:0] grp_Inverse_fu_145_ap_return_0;
wire   [7:0] grp_Inverse_fu_145_ap_return_1;
wire    grp_Inverse_fu_145_ap_ext_blocking_n;
wire    grp_Inverse_fu_145_ap_str_blocking_n;
wire    grp_Inverse_fu_145_ap_int_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_idle;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ready;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0;
wire   [31:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0;
wire   [31:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_idle;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ready;
wire   [12:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_we0;
wire   [31:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_d0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_we0;
wire   [31:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_d0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_idle;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ready;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0;
wire   [31:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0;
wire   [31:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0;
wire   [17:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_we0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_d0;
wire   [17:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_address0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_ce0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_we0;
wire   [8:0] grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_d0;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n;
wire    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n;
reg    grp_Inverse_fu_145_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    ap_block_state3_on_subcall_done;
reg    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg;
reg    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire   [63:0] idxprom24_i_fu_358_p1;
reg   [15:0] i_fu_96;
wire   [15:0] i_8_fu_310_p2;
reg    ap_block_state1;
wire  signed [8:0] sext_ln223_1_fu_222_p1;
wire  signed [9:0] sext_ln223_2_fu_240_p1;
wire  signed [9:0] sext_ln223_fu_236_p1;
wire    ap_CS_fsm_state5;
wire  signed [31:0] sext_ln223_3_fu_264_p1;
wire   [63:0] zext_ln222_fu_278_p1;
wire   [63:0] zext_ln223_fu_267_p1;
wire   [63:0] lshr_ln223_fu_281_p2;
wire   [16:0] zext_ln232_2_fu_301_p1;
wire   [16:0] a_fu_316_p2;
wire   [7:0] empty_fu_329_p1;
wire   [0:0] tmp_7_fu_321_p3;
wire   [7:0] empty_66_fu_333_p2;
wire   [15:0] grp_fu_362_p0;
wire   [15:0] grp_fu_362_p1;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_int_blocking_cur_n;
reg    ap_ext_blocking_sub_n;
reg    ap_wait_0;
reg    ap_sub_ext_blocking_0;
reg    ap_wait_1;
reg    ap_sub_ext_blocking_1;
reg    ap_wait_2;
reg    ap_sub_ext_blocking_2;
reg    ap_wait_3;
reg    ap_sub_ext_blocking_3;
reg    ap_str_blocking_sub_n;
reg    ap_sub_str_blocking_0;
reg    ap_sub_str_blocking_1;
reg    ap_sub_str_blocking_2;
reg    ap_sub_str_blocking_3;
reg    ap_int_blocking_sub_n;
reg    ap_sub_int_blocking_0;
reg    ap_sub_int_blocking_1;
reg    ap_sub_int_blocking_2;
reg    ap_sub_int_blocking_3;
wire   [18:0] grp_fu_362_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 14'd1;
#0 grp_Inverse_fu_145_ap_start_reg = 1'b0;
#0 grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg = 1'b0;
#0 grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg = 1'b0;
#0 grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg = 1'b0;
end

mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_histdEe #(
    .DataWidth( 16 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
xFTrackmulKernelLut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(xFTrackmulKernelLut_address0),
    .ce0(xFTrackmulKernelLut_ce0),
    .q0(xFTrackmulKernelLut_q0)
);

mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s_tmp_hist1 #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
tmp_hist1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist1_address0),
    .ce0(tmp_hist1_ce0),
    .we0(tmp_hist1_we0),
    .d0(tmp_hist1_d0),
    .q0(tmp_hist1_q0)
);

mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s_tmp_hist1 #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
tmp_hist2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_hist2_address0),
    .ce0(tmp_hist2_ce0),
    .we0(tmp_hist2_we0),
    .d0(tmp_hist2_d0),
    .q0(tmp_hist2_q0)
);

mean_shift_accel_Inverse grp_Inverse_fu_145(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Inverse_fu_145_ap_start),
    .ap_done(grp_Inverse_fu_145_ap_done),
    .ap_idle(grp_Inverse_fu_145_ap_idle),
    .ap_ready(grp_Inverse_fu_145_ap_ready),
    .x(grp_Inverse_fu_145_x),
    .ap_return_0(grp_Inverse_fu_145_ap_return_0),
    .ap_return_1(grp_Inverse_fu_145_ap_return_1),
    .ap_ext_blocking_n(grp_Inverse_fu_145_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_Inverse_fu_145_ap_str_blocking_n),
    .ap_int_blocking_n(grp_Inverse_fu_145_ap_int_blocking_n)
);

mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start),
    .ap_done(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done),
    .ap_idle(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_idle),
    .ap_ready(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ready),
    .tmp_hist1_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0),
    .tmp_hist1_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0),
    .tmp_hist1_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0),
    .tmp_hist1_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0),
    .tmp_hist2_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0),
    .tmp_hist2_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0),
    .tmp_hist2_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0),
    .tmp_hist2_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0),
    .ap_ext_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n),
    .ap_int_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n)
);

mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start),
    .ap_done(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done),
    .ap_idle(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_idle),
    .ap_ready(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ready),
    .zext_ln268(tmp_reg_427),
    .Qu_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_address0),
    .Qu_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_ce0),
    .Qu_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_we0),
    .Qu_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_d0),
    .tmp_hist1_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0),
    .tmp_hist1_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0),
    .tmp_hist1_q0(tmp_hist1_q0),
    .tmp_hist2_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0),
    .tmp_hist2_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0),
    .tmp_hist2_q0(tmp_hist2_q0),
    .cmp49(cmp49_reg_465),
    .Pu_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_address0),
    .Pu_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_ce0),
    .Pu_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_we0),
    .Pu_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_d0),
    .ap_ext_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n),
    .ap_int_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n)
);

mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start),
    .ap_done(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done),
    .ap_idle(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_idle),
    .ap_ready(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ready),
    .input21_dout(input21_dout),
    .input21_empty_n(input21_empty_n),
    .input21_read(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read),
    .buf_size(buf_size_reg_437),
    .zext_ln222(h_x_reg_390),
    .yy_cast(xFTrackmulKernelLut_load_reg_480),
    .wh(wh_reg_442),
    .tmp_hist1_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0),
    .tmp_hist1_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0),
    .tmp_hist1_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0),
    .tmp_hist1_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0),
    .tmp_hist1_q0(tmp_hist1_q0),
    .tmp_hist2_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0),
    .tmp_hist2_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0),
    .tmp_hist2_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0),
    .tmp_hist2_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0),
    .tmp_hist2_q0(tmp_hist2_q0),
    .y_off(y_off_reg_475),
    .BIN_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_address0),
    .BIN_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_ce0),
    .BIN_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_we0),
    .BIN_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_d0),
    .BIN1_address0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_address0),
    .BIN1_ce0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_ce0),
    .BIN1_we0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_we0),
    .BIN1_d0(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_d0),
    .ap_ext_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n),
    .ap_str_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n),
    .ap_int_blocking_n(grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n)
);

mean_shift_accel_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U85(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_width1_reg_407),
    .din1(p_height1_reg_397),
    .ce(1'b1),
    .dout(grp_fu_249_p2)
);

mean_shift_accel_mul_mul_16ns_16ns_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 19 ))
mul_mul_16ns_16ns_19_4_1_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_362_p0),
    .din1(grp_fu_362_p1),
    .ce(1'b1),
    .dout(grp_fu_362_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Inverse_fu_145_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3)))) begin
            grp_Inverse_fu_145_ap_start_reg <= 1'b1;
        end else if ((grp_Inverse_fu_145_ap_ready == 1'b1)) begin
            grp_Inverse_fu_145_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln232_fu_305_p2 == 1'd1))) begin
            grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ready == 1'b1)) begin
            grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ready == 1'b1)) begin
            grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ready == 1'b1)) begin
            grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((obj_wdt_empty_n == 1'b0) | (obj_hgt_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_96 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln232_fu_305_p2 == 1'd0))) begin
        i_fu_96 <= i_8_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln223_1_reg_412 <= add_ln223_1_fu_243_p2;
        p_width1_reg_407 <= grp_Inverse_fu_145_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln223_reg_402 <= add_ln223_fu_226_p2;
        p_height1_reg_397 <= grp_Inverse_fu_145_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_size_reg_437[15 : 1] <= buf_size_fu_271_p3[15 : 1];
        tmp_reg_427[12 : 9] <= tmp_fu_253_p3[12 : 9];
        wh_reg_442 <= wh_fu_287_p1;
        zext_ln214_reg_432[15 : 0] <= zext_ln214_fu_261_p1[15 : 0];
        zext_ln232_1_reg_447[14 : 0] <= zext_ln232_1_fu_291_p1[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln232_fu_305_p2 == 1'd1))) begin
        cmp49_reg_465 <= cmp49_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        h_x_reg_390 <= {{obj_wdt_dout[15:1]}};
        h_y_reg_384 <= {{obj_hgt_dout[15:1]}};
        obj_hgt_read_reg_379 <= obj_hgt_dout;
        obj_wdt_read_reg_374 <= obj_wdt_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_reg_417 <= grp_fu_249_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        xFTrackmulKernelLut_load_reg_480 <= xFTrackmulKernelLut_q0;
        y_off_reg_475 <= grp_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln232_fu_305_p2 == 1'd0))) begin
        y_2_reg_460 <= y_2_fu_339_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if (((obj_wdt_empty_n == 1'b0) | (obj_hgt_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Inverse_fu_145_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if ((((ap_wait_3 & ap_sub_ext_blocking_3) == 1'b1) & ((ap_wait_2 & ap_sub_ext_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_ext_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_ext_blocking_0) == 1'b1))) begin
        ap_ext_blocking_sub_n = 1'b0;
    end else begin
        ap_ext_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_3 & ap_sub_int_blocking_3) == 1'b1) & ((ap_wait_2 & ap_sub_int_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_int_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_int_blocking_0) == 1'b1))) begin
        ap_int_blocking_sub_n = 1'b0;
    end else begin
        ap_int_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_wait_3 & ap_sub_str_blocking_3) == 1'b1) & ((ap_wait_2 & ap_sub_str_blocking_2) == 1'b1) & ((ap_wait_1 & ap_sub_str_blocking_1) == 1'b1) & ((ap_wait_0 & ap_sub_str_blocking_0) == 1'b1))) begin
        ap_str_blocking_sub_n = 1'b0;
    end else begin
        ap_str_blocking_sub_n = 1'b1;
    end
end

always @ (*) begin
    if ((grp_Inverse_fu_145_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_0 = 1'b1;
    end else begin
        ap_sub_ext_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_1 = 1'b1;
    end else begin
        ap_sub_ext_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_2 = 1'b1;
    end else begin
        ap_sub_ext_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_ext_blocking_n == 1'b0)) begin
        ap_sub_ext_blocking_3 = 1'b1;
    end else begin
        ap_sub_ext_blocking_3 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Inverse_fu_145_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_0 = 1'b1;
    end else begin
        ap_sub_int_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_1 = 1'b1;
    end else begin
        ap_sub_int_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_2 = 1'b1;
    end else begin
        ap_sub_int_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_int_blocking_n == 1'b0)) begin
        ap_sub_int_blocking_3 = 1'b1;
    end else begin
        ap_sub_int_blocking_3 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Inverse_fu_145_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_0 = 1'b1;
    end else begin
        ap_sub_str_blocking_0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_1 = 1'b1;
    end else begin
        ap_sub_str_blocking_1 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_2 = 1'b1;
    end else begin
        ap_sub_str_blocking_2 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_str_blocking_n == 1'b0)) begin
        ap_sub_str_blocking_3 = 1'b1;
    end else begin
        ap_sub_str_blocking_3 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state3 == ap_CS_fsm)) begin
        ap_wait_0 = 1'b1;
    end else begin
        ap_wait_0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state3 == ap_CS_fsm)) begin
        ap_wait_1 = 1'b1;
    end else begin
        ap_wait_1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state14 == ap_CS_fsm)) begin
        ap_wait_2 = 1'b1;
    end else begin
        ap_wait_2 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_ST_fsm_state13 == ap_CS_fsm)) begin
        ap_wait_3 = 1'b1;
    end else begin
        ap_wait_3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_Inverse_fu_145_x = h_x_reg_390;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_Inverse_fu_145_x = h_y_reg_384;
    end else begin
        grp_Inverse_fu_145_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        input21_read = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_input21_read;
    end else begin
        input21_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        obj_hgt_blk_n = obj_hgt_empty_n;
    end else begin
        obj_hgt_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((obj_wdt_empty_n == 1'b0) | (obj_hgt_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        obj_hgt_read = 1'b1;
    end else begin
        obj_hgt_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        obj_wdt_blk_n = obj_wdt_empty_n;
    end else begin
        obj_wdt_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((obj_wdt_empty_n == 1'b0) | (obj_hgt_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        obj_wdt_read = 1'b1;
    end else begin
        obj_wdt_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist1_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_hist1_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_address0;
    end else begin
        tmp_hist1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist1_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_hist1_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_ce0;
    end else begin
        tmp_hist1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist1_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_d0;
    end else begin
        tmp_hist1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist1_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist1_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist1_we0;
    end else begin
        tmp_hist1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist2_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_hist2_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist2_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_address0;
    end else begin
        tmp_hist2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist2_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_hist2_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_tmp_hist2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist2_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_ce0;
    end else begin
        tmp_hist2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist2_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist2_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_d0;
    end else begin
        tmp_hist2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_hist2_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_tmp_hist2_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_hist2_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_tmp_hist2_we0;
    end else begin
        tmp_hist2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        xFTrackmulKernelLut_address0 = idxprom24_i_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        xFTrackmulKernelLut_address0 = 8'd0;
    end else begin
        xFTrackmulKernelLut_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        xFTrackmulKernelLut_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        xFTrackmulKernelLut_ce0 = 1'b0;
    end else begin
        xFTrackmulKernelLut_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((obj_wdt_empty_n == 1'b0) | (obj_hgt_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_Inverse_fu_145_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln232_fu_305_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BIN1_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_address0;

assign BIN1_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_ce0;

assign BIN1_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_d0;

assign BIN1_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN1_we0;

assign BIN_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_address0;

assign BIN_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_ce0;

assign BIN_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_d0;

assign BIN_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_BIN_we0;

assign Pu_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_address0;

assign Pu_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_ce0;

assign Pu_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_d0;

assign Pu_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Pu_we0;

assign Qu_address0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_address0;

assign Qu_ce0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_ce0;

assign Qu_d0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_d0;

assign Qu_we0 = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_Qu_we0;

assign a_fu_316_p2 = (zext_ln232_2_fu_301_p1 - zext_ln232_1_reg_447);

assign add_ln223_1_fu_243_p2 = ($signed(sext_ln223_2_fu_240_p1) + $signed(sext_ln223_fu_236_p1));

assign add_ln223_fu_226_p2 = ($signed(sext_ln223_1_fu_222_p1) + $signed(9'd496));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((obj_wdt_empty_n == 1'b0) | (obj_hgt_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_done == 1'b0) | (grp_Inverse_fu_145_ap_done == 1'b0));
end

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & 1'b1);

assign ap_int_blocking_cur_n = (obj_wdt_blk_n & obj_hgt_blk_n);

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_str_blocking_n = (ap_str_blocking_sub_n & 1'b1);

assign buf_size_fu_271_p3 = {{h_x_reg_390}, {1'd0}};

assign cmp49_fu_352_p2 = ((p_read1 == 8'd0) ? 1'b1 : 1'b0);

assign empty_66_fu_333_p2 = (8'd0 - empty_fu_329_p1);

assign empty_fu_329_p1 = a_fu_316_p2[7:0];

assign grp_Inverse_fu_145_ap_start = grp_Inverse_fu_145_ap_start_reg;

assign grp_fu_362_p0 = grp_fu_362_p00;

assign grp_fu_362_p00 = i_fu_96;

assign grp_fu_362_p1 = zext_ln214_reg_432;

assign grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate_fu_158_ap_start_reg;

assign grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_init_fu_152_ap_start_reg;

assign grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start = grp_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_width_fu_170_ap_start_reg;

assign i_8_fu_310_p2 = (i_fu_96 + 16'd1);

assign icmp_ln232_fu_305_p2 = ((i_fu_96 == obj_hgt_read_reg_379) ? 1'b1 : 1'b0);

assign idxprom24_i_fu_358_p1 = y_2_reg_460;

assign lshr_ln223_fu_281_p2 = zext_ln222_fu_278_p1 >> zext_ln223_fu_267_p1;

assign sext_ln223_1_fu_222_p1 = $signed(grp_Inverse_fu_145_ap_return_1);

assign sext_ln223_2_fu_240_p1 = $signed(add_ln223_reg_402);

assign sext_ln223_3_fu_264_p1 = $signed(add_ln223_1_reg_412);

assign sext_ln223_fu_236_p1 = $signed(grp_Inverse_fu_145_ap_return_1);

assign tmp_7_fu_321_p3 = a_fu_316_p2[32'd16];

assign tmp_fu_253_p3 = {{p_read}, {9'd0}};

assign wh_fu_287_p1 = lshr_ln223_fu_281_p2[23:0];

assign y_2_fu_339_p3 = ((tmp_7_fu_321_p3[0:0] == 1'b1) ? empty_66_fu_333_p2 : empty_fu_329_p1);

assign zext_ln214_fu_261_p1 = obj_wdt_read_reg_374;

assign zext_ln222_fu_278_p1 = temp_reg_417;

assign zext_ln223_fu_267_p1 = $unsigned(sext_ln223_3_fu_264_p1);

assign zext_ln232_1_fu_291_p1 = h_y_reg_384;

assign zext_ln232_2_fu_301_p1 = i_fu_96;

always @ (posedge ap_clk) begin
    tmp_reg_427[8:0] <= 9'b000000000;
    zext_ln214_reg_432[18:16] <= 3'b000;
    buf_size_reg_437[0] <= 1'b0;
    zext_ln232_1_reg_447[16:15] <= 2'b00;
end

endmodule //mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_s
