// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln268,
        Qu_address0,
        Qu_ce0,
        Qu_we0,
        Qu_d0,
        tmp_hist1_address0,
        tmp_hist1_ce0,
        tmp_hist1_q0,
        tmp_hist2_address0,
        tmp_hist2_ce0,
        tmp_hist2_q0,
        cmp49,
        Pu_address0,
        Pu_ce0,
        Pu_we0,
        Pu_d0,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [12:0] zext_ln268;
output  [12:0] Qu_address0;
output   Qu_ce0;
output   Qu_we0;
output  [31:0] Qu_d0;
output  [8:0] tmp_hist1_address0;
output   tmp_hist1_ce0;
input  [31:0] tmp_hist1_q0;
output  [8:0] tmp_hist2_address0;
output   tmp_hist2_ce0;
input  [31:0] tmp_hist2_q0;
input  [0:0] cmp49;
output  [8:0] Pu_address0;
output   Pu_ce0;
output   Pu_we0;
output  [31:0] Pu_d0;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_idle;
reg Qu_ce0;
reg Qu_we0;
reg tmp_hist1_ce0;
reg tmp_hist2_ce0;
reg Pu_ce0;
reg Pu_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln261_fu_117_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] cmp49_read_reg_167;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln270_fu_129_p1;
reg   [63:0] zext_ln270_reg_175;
reg   [63:0] zext_ln270_reg_175_pp0_iter1_reg;
wire   [12:0] add_ln268_fu_139_p2;
reg   [12:0] add_ln268_reg_180;
reg   [12:0] Qu_addr_reg_195;
wire   [31:0] add_ln270_fu_154_p2;
reg   [31:0] add_ln270_reg_200;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln268_2_fu_150_p1;
reg   [9:0] i_fu_42;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_5;
wire   [9:0] i_6_fu_123_p2;
wire   [12:0] zext_ln268_1_fu_135_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

mean_shift_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln261_fu_117_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_42 <= i_6_fu_123_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_42 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Qu_addr_reg_195 <= zext_ln268_2_fu_150_p1;
        add_ln270_reg_200 <= add_ln270_fu_154_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        zext_ln270_reg_175_pp0_iter1_reg[9 : 0] <= zext_ln270_reg_175[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln261_fu_117_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln268_reg_180 <= add_ln268_fu_139_p2;
        zext_ln270_reg_175[9 : 0] <= zext_ln270_fu_129_p1[9 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Pu_ce0 = 1'b1;
    end else begin
        Pu_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp49_read_reg_167 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Pu_we0 = 1'b1;
    end else begin
        Pu_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Qu_ce0 = 1'b1;
    end else begin
        Qu_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp49_read_reg_167 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        Qu_we0 = 1'b1;
    end else begin
        Qu_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln261_fu_117_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_5 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_42;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_hist1_ce0 = 1'b1;
    end else begin
        tmp_hist1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_hist2_ce0 = 1'b1;
    end else begin
        tmp_hist2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Pu_address0 = zext_ln270_reg_175_pp0_iter1_reg;

assign Pu_d0 = add_ln270_reg_200;

assign Qu_address0 = Qu_addr_reg_195;

assign Qu_d0 = add_ln270_reg_200;

assign add_ln268_fu_139_p2 = (zext_ln268 + zext_ln268_1_fu_135_p1);

assign add_ln270_fu_154_p2 = (tmp_hist2_q0 + tmp_hist1_q0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_n = (1'b1 & 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign cmp49_read_reg_167 = cmp49;

assign i_6_fu_123_p2 = (ap_sig_allocacmp_i_5 + 10'd1);

assign icmp_ln261_fu_117_p2 = ((ap_sig_allocacmp_i_5 == 10'd512) ? 1'b1 : 1'b0);

assign tmp_hist1_address0 = zext_ln270_fu_129_p1;

assign tmp_hist2_address0 = zext_ln270_fu_129_p1;

assign zext_ln268_1_fu_135_p1 = ap_sig_allocacmp_i_5;

assign zext_ln268_2_fu_150_p1 = add_ln268_reg_180;

assign zext_ln270_fu_129_p1 = ap_sig_allocacmp_i_5;

always @ (posedge ap_clk) begin
    zext_ln270_reg_175[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    zext_ln270_reg_175_pp0_iter1_reg[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //mean_shift_accel_xFTrackmulHist_550_299_598_1_9_unsigned_int_unsigned_short_Pipeline_loop_hist_accumulate
